### ISSUE TITLE
Misleading SAS log about "Authentication is not needed"

### ISSUE THREAD

**Issue by mirw** [Metaswitch/clearwater-sas-resources#93]
#### Symptoms

When investigating a failed registration, we saw a SAS log that said

```
Authentication is not needed as the request wasn't received on the S-CSCF port
```

In fact, authentication **was** needed - it just wasn't provided by the I-CSCF.  (The S-CSCF would go on to do authentication.)

#### Impact

Confusion when troubleshooting issues.

#### Release and environment 

release-95

#### Steps to reproduce

Try to REGISTER a UE and look at the SAS logs.

**Comment by graemerobertson** [comment]
@rkd-msw is this something you've been looking at recently?

**Comment by rkd-msw** [comment]
Don't think it is. However, the fix looks obvious to me:

* we know when I-CSCF processing is happening because of logs like https://github.com/Metaswitch/clearwater-sas-resources/blob/master/clearwater_sas_resource_bundle.yaml#L1077
* we know that I-CSCFs don't authenticate messages
* so the "Authentication is not needed as the request wasn't received on the S-CSCF port" log isn't adding any value
* so we should just delete it
